version: '3'
services:
  gcc-cpp-sample:
    # image: 'gcc:9.2'
    image: 'gcc'
    volumes:
      - .:/src/cpp
    working_dir: /src/cpp
    command:  bash -c "chmod 755 ./build.sh  && ./build.sh"
    deploy:
      resources:
        limits:
          # cpus: "1"
          # cpus: "2"
          cpus: "4"