version: '3'
services:
  experiment:
    # image: 'gcc:1.2'
    image: silkeh/clang
    volumes:
      - .:/src/cpp
    working_dir: /src/cpp
    command:  bash -c "chmod 755 ./build.sh  && ./build.sh"
    deploy:
      resources:
        limits:
          cpus: "4"
          # cpus: "1"
          # cpus: "2"
          # cpus: "4"